services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/envs/backend.env
      - ./backend/envs/postgres.env
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - backend_db_network
    depends_on:
      - backend_db

  backend_db:
    image: postgres:15.3
    volumes:
      - backend_db_volume:/var/lib/postgresql/data
    env_file:
      - ./backend/envs/postgres.env
    ports:
      - 5432:5432
    networks:
      - backend_db_network


networks:
  backend_db_network:
    driver: bridge

volumes:
  backend_db_volume: